name: tizonia
version: 0.7.0
summary: Tizonia command-line cloud music player.
description: Command-line cloud music player with support for Spotify, Google Play Music, YouTube, SoundCloud and Dirble.
grade: devel
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
  tizonia:
    command: ./bin/tizonia
    plugs:
      - home
      - network
      - network-bind
      - pulseaudio
      - removable-media

parts:
  pypideps:
    plugin: python
    python-version: python2
    python-packages:
      - soundcloud
      - gmusicapi
      - youtube-dl
      - pafy
    filesets:
      modules:
        - lib/python2.7/dist-packages/*
    stage:
      - $modules
    prime:
      - $modules
  tizonia:
    plugin: autotools
    source: https://github.com/tizonia/tizonia-openmax-il.git
    configflags: [--silent, --enable-silent-rules]
    build-packages:
      - build-essential
      - autoconf
      - autoconf-archive
      - automake
      - autotools-dev
      - libtool
      - libmad0-dev
      - liblog4c-dev
      - libasound2-dev
      - libdbus-1-dev
      - libdbus-c++-dev
      - libsqlite3-dev
      - libboost-all-dev
      - uuid-dev
      - libsdl1.2-dev
      - libvpx-dev
      - libmp3lame-dev
      - libfaad-dev
      - libev-dev
      - libtag1-dev
      - libfishsound1-dev
      - libmediainfo-dev
      - libcurl4-openssl-dev
      - libpulse-dev
      - libmpg123-dev
      - libvorbis-dev
      - libopus-dev
      - libopusfile-dev
      - libogg-dev
      - libflac-dev
      - liboggz2-dev
      - libsndfile1-dev
      - libspotify-dev
      - libffi-dev
      - libssl-dev
      - python-dev
      - python-setuptools
      - python-pip
      - python-decorator
      - python-protobuf
      - python-validictory
      - python-bs4
      - python-oauth2client
      - python-dateutil
      - python-mutagen
      - python-crypto
      - python-requests
      - curl
      - check
      - wget
      - sqlite3
      - dbus-x11
    after:
      - pypideps
    filesets:
      binaries:
        - bin/*
      headers:
        - include/tizonia/*
      modules:
        - lib/python2.7/dist-packages/*
      libraries:
        - lib/lib*
    stage:
      - $binaries
      - $headers
      - $modules
      - $libraries
    prime:
      - $binaries
      - $headers
      - $modules
      - $libraries
  env:
    plugin: nil
    stage-packages:
      - libmad0
      - liblog4c3
      - libasound2
      - libdbus-1-3
      - libdbus-c++-1-0v5
      - libdbus-c++-bin
      - libsqlite3-0
      - libboost-all-dev
      - uuid-runtime
      - libsdl1.2debian
      - libvpx3
      - libmp3lame0
      - libfaad2
      - libev4
      - libtag1v5
      - libfishsound1
      - libmediainfo0v5
      - libcurl4-openssl-dev
      - libmpg123-0
      - libvorbis0a
      - libopus0
      - libopusfile0
      - libogg0
      - libflac8
      - liboggz2
      - libsndfile1
      - libspotify12
      - libffi6
      - libssl1.0.0
      - sqlite3
      - dbus-x11
    after:
      - tizonia
